// ── Generated by: omega kompile examples/tcp-server.omega --theory TcpServer ──
// ── Do not edit. Regenerate from the verified Omega theory. ──

pub mod omega_generated;
pub use omega_generated::*;
