// ── Generated by: omega kompile examples/tcp-server.omega --theory TcpServer ──
// ── Do not edit. Regenerate from the verified Omega theory. ──

#[derive(Debug, Clone, PartialEq)]
pub enum State {
    Closed,
    Listen,
    SynRecvd,
    Established,
    FinWait,
}

#[derive(Debug, Clone, PartialEq)]
pub enum Event {
    EvListen,
    EvSyn,
    EvAck,
    EvData,
    EvFin,
    EvRst,
}

#[derive(Debug, Clone, PartialEq)]
pub enum Bool {
    True,
    False,
}

pub trait TcpServerEffects {
    fn eff_bind_port(&mut self);
    fn eff_send_syn_ack(&mut self);
    fn eff_send_data(&mut self, state: State);
    fn eff_send_fin(&mut self);
    fn eff_send_rst(&mut self);
    fn eff_log(&mut self, state: State, event: Event, state1: State);
}

pub fn can_send(state: State) -> Bool {
    match state {
        State::Established => Bool::True,
        State::Closed => Bool::False,
        State::Listen => Bool::False,
        State::SynRecvd => Bool::False,
        State::FinWait => Bool::False,
        _ => unreachable!(),
    }
}

pub fn is_open(state: State) -> Bool {
    match state {
        State::Established => Bool::True,
        State::SynRecvd => Bool::True,
        State::Closed => Bool::False,
        State::Listen => Bool::False,
        State::FinWait => Bool::False,
        _ => unreachable!(),
    }
}

pub fn on_event(effects: &mut impl TcpServerEffects, state: State, event: Event) {
    match (state, event) {
        (State::Closed, Event::EvListen) => effects.eff_bind_port(),
        (State::Listen, Event::EvSyn) => effects.eff_send_syn_ack(),
        (State::SynRecvd, Event::EvAck) => effects.eff_log(State::SynRecvd, Event::EvAck, State::Established),
        (State::Established, Event::EvData) => effects.eff_send_data(State::Established),
        (State::Established, Event::EvFin) => effects.eff_send_fin(),
        (State::Established, Event::EvRst) => effects.eff_send_rst(),
        (State::FinWait, Event::EvAck) => effects.eff_log(State::FinWait, Event::EvAck, State::Closed),
        (State::Listen, Event::EvRst) => effects.eff_send_rst(),
        (State::SynRecvd, Event::EvRst) => effects.eff_send_rst(),
        (State::FinWait, Event::EvRst) => effects.eff_send_rst(),
        _ => unreachable!(),
    }
}

pub fn step(state: State, event: Event) -> State {
    match (state, event) {
        (State::Closed, Event::EvListen) => State::Listen,
        (State::Listen, Event::EvSyn) => State::SynRecvd,
        (State::SynRecvd, Event::EvAck) => State::Established,
        (State::Established, Event::EvData) => State::Established,
        (State::Established, Event::EvFin) => State::FinWait,
        (State::FinWait, Event::EvAck) => State::Closed,
        (State::Listen, Event::EvRst) => State::Closed,
        (State::SynRecvd, Event::EvRst) => State::Closed,
        (State::Established, Event::EvRst) => State::Closed,
        (State::FinWait, Event::EvRst) => State::Closed,
        _ => unreachable!(),
    }
}
