//! SMT bridge: encode Sexp terms to SMT-LIB2, communicate with Z3,
//! and inject results back into the proof system.
//!
//! Three modes:
//! - **SMTOracle**: terminal decision procedure. Serialize goal to SMT-LIB2,
//!   get sat/unsat back. No e-graph.
//! - **SMTAssisted**: cooperative mode. E-graph runs normally, calls Z3
//!   for decidable fragments, injects equalities back.
//! - **SMTEncoding**: the AST→SMT-LIB2 serializer (used by both modes).

use apeiron::parser::{Sexp, Span};
use std::collections::{HashMap, HashSet};
use std::io::Write;
use std::process::{Command, Stdio};

/// SMT-LIB2 sort declaration
#[derive(Debug, Clone)]
pub struct SmtSort {
    pub name: String,
}

/// SMT-LIB2 function declaration
#[derive(Debug, Clone)]
pub struct SmtFunc {
    pub name: String,
    pub arg_sorts: Vec<String>,
    pub ret_sort: String,
}

/// Result from an SMT query
#[derive(Debug, Clone, PartialEq)]
pub enum SmtResult {
    Sat,
    Unsat,
    Unknown,
    Error(String),
}

/// Encode a set of theory declarations and an assertion into SMT-LIB2.
pub fn encode_smtlib2(
    sorts: &[SmtSort],
    funcs: &[SmtFunc],
    assertions: &[String],
    check_sat: bool,
) -> String {
    let mut out = String::new();
    out.push_str("; Auto-generated by Hyperion SMT bridge\n");
    out.push_str("(set-option :rlimit 1000000)\n"); // Prevent quantifier instantiation loops
    out.push_str("(set-logic ALL)\n");

    // Declare sorts
    for sort in sorts {
        out.push_str(&format!("(declare-sort {} 0)\n", sort.name));
    }

    // Declare functions
    for func in funcs {
        let args = if func.arg_sorts.is_empty() {
            "()".to_string()
        } else {
            format!("({})", func.arg_sorts.join(" "))
        };
        out.push_str(&format!(
            "(declare-fun {} {} {})\n",
            func.name, args, func.ret_sort
        ));
    }

    // Assertions
    for assertion in assertions {
        out.push_str(&format!("(assert {})\n", assertion));
    }

    if check_sat {
        out.push_str("(check-sat)\n");
    }

    out
}

/// Convert a Hyperion Sexp term to SMT-LIB2 s-expression string.
/// Hyperion uses `[f a b]` brackets; SMT-LIB2 uses `(f a b)` parens.
pub fn sexp_to_smtlib2(sexp: &Sexp) -> String {
    match sexp {
        Sexp::Atom(name, _) => {
            // SMT-LIB2 doesn't like `?` prefix for variables
            if name.starts_with('?') {
                name[1..].to_string()
            } else {
                name.clone()
            }
        }
        Sexp::List(items, _) => {
            if items.is_empty() {
                return "()".to_string();
            }
            let parts: Vec<String> = items.iter().map(|i| sexp_to_smtlib2(i)).collect();
            format!("({})", parts.join(" "))
        }
    }
}

/// Extract sorts and functions from a VonNeumann theory for SMT encoding.
pub fn theory_to_smt_decls(
    sorts: &[String],
    morphism_types: &HashMap<String, (Vec<String>, String)>,
) -> (Vec<SmtSort>, Vec<SmtFunc>) {
    let smt_sorts: Vec<SmtSort> = sorts
        .iter()
        .map(|s| SmtSort { name: s.clone() })
        .collect();

    let smt_funcs: Vec<SmtFunc> = morphism_types
        .iter()
        .map(|(name, (args, ret))| SmtFunc {
            name: name.clone(),
            arg_sorts: args.clone(),
            ret_sort: ret.clone(),
        })
        .collect();

    (smt_sorts, smt_funcs)
}

/// Encode an assert-eq as an SMT validity check.
/// To prove `lhs = rhs`, we assert `(not (= lhs rhs))` and check for unsat.
pub fn encode_equality_check(
    sorts: &[SmtSort],
    funcs: &[SmtFunc],
    lhs: &Sexp,
    rhs: &Sexp,
    free_vars: &[(String, String)], // (var_name, sort)
) -> String {
    let mut out = encode_smtlib2(sorts, funcs, &[], false);

    // Declare free variables
    for (var, sort) in free_vars {
        out.push_str(&format!("(declare-const {} {})\n", var, sort));
    }

    // Assert negation of equality (prove by refutation)
    let lhs_smt = sexp_to_smtlib2(lhs);
    let rhs_smt = sexp_to_smtlib2(rhs);
    out.push_str(&format!("(assert (not (= {} {})))\n", lhs_smt, rhs_smt));
    out.push_str("(check-sat)\n");

    out
}

/// Default Z3 timeout in seconds.
const Z3_TIMEOUT_SECS: u64 = 10;

/// Run Z3 on an SMT-LIB2 input string.
/// Returns the result (sat/unsat/unknown).
/// Enforces a timeout to prevent Z3 from hanging on quantifier instantiation loops.
pub fn run_z3(input: &str) -> SmtResult {
    run_z3_with_timeout(input, Z3_TIMEOUT_SECS)
}

/// Run Z3 with an explicit timeout in seconds.
pub fn run_z3_with_timeout(input: &str, timeout_secs: u64) -> SmtResult {
    let result = Command::new("z3")
        .arg("-in")
        .arg(format!("-T:{}", timeout_secs))
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn();

    let mut child = match result {
        Ok(c) => c,
        Err(e) => return SmtResult::Error(format!("failed to spawn z3: {}", e)),
    };

    // Write input to stdin
    if let Some(mut stdin) = child.stdin.take() {
        if let Err(e) = stdin.write_all(input.as_bytes()) {
            return SmtResult::Error(format!("failed to write to z3 stdin: {}", e));
        }
    }

    // Wait with a Rust-side timeout as a safety net beyond Z3's -T flag
    let deadline = std::time::Instant::now() + std::time::Duration::from_secs(timeout_secs + 5);
    loop {
        match child.try_wait() {
            Ok(Some(_status)) => break,
            Ok(None) => {
                if std::time::Instant::now() > deadline {
                    let _ = child.kill();
                    let _ = child.wait();
                    return SmtResult::Error("z3 timeout: killed after deadline".to_string());
                }
                std::thread::sleep(std::time::Duration::from_millis(50));
            }
            Err(e) => return SmtResult::Error(format!("z3 process error: {}", e)),
        }
    }

    let output = match child.wait_with_output() {
        Ok(o) => o,
        Err(e) => return SmtResult::Error(format!("z3 process error: {}", e)),
    };

    let stdout = String::from_utf8_lossy(&output.stdout);
    let first_line = stdout.lines().next().unwrap_or("").trim();

    match first_line {
        "sat" => SmtResult::Sat,
        "unsat" => SmtResult::Unsat,
        "unknown" => SmtResult::Unknown,
        "timeout" => SmtResult::Unknown, // Z3 -T timeout returns "timeout"
        _ => SmtResult::Error(format!("unexpected z3 output: {}", stdout)),
    }
}

/// Prove an equality using Z3 (SMT oracle mode).
/// Returns Ok(()) if proved, Err(detail) if disproved or unknown.
pub fn prove_equality_z3(
    sorts: &[SmtSort],
    funcs: &[SmtFunc],
    lhs: &Sexp,
    rhs: &Sexp,
) -> Result<(), String> {
    // Collect free variables from both sides
    let mut free_vars = HashSet::new();
    collect_free_vars(lhs, &mut free_vars);
    collect_free_vars(rhs, &mut free_vars);

    // For now, assign all free vars to the first sort (simplified)
    let default_sort = sorts.first().map(|s| s.name.clone()).unwrap_or("Int".to_string());
    let var_decls: Vec<(String, String)> = free_vars
        .into_iter()
        .map(|v| (v, default_sort.clone()))
        .collect();

    let smtlib = encode_equality_check(sorts, funcs, lhs, rhs, &var_decls);
    let result = run_z3(&smtlib);

    match result {
        SmtResult::Unsat => Ok(()), // negation is unsat → equality holds
        SmtResult::Sat => Err("Z3: equality is falsifiable (sat)".to_string()),
        SmtResult::Unknown => Err("Z3: unknown (solver timeout or undecidable)".to_string()),
        SmtResult::Error(e) => Err(format!("Z3 error: {}", e)),
    }
}

/// Known HoTT path-space constructors that are proof-relevant.
/// Sending these to Z3 would collapse higher homotopies (Axiom K contagion).
const HOTT_PATH_CONSTRUCTORS: &[&str] = &[
    "refl", "concat", "inv", "ap", "transport", "apd",
    "path", "Path", "PathP", "pathp",
    "hcomp", "coe", "transp", "comp",
    "loop", "merid", "glue", "unglue",
    "seg", "surf", "hub", "spoke",
];

/// Check if a term contains HoTT path constructors that are proof-relevant.
/// Such terms must NOT be sent to Z3 (which is proof-irrelevant and would
/// silently impose Axiom K, collapsing the ∞-topos to a 1-groupoid).
pub fn contains_path_constructors(sexp: &Sexp) -> bool {
    match sexp {
        Sexp::Atom(name, _) => HOTT_PATH_CONSTRUCTORS.contains(&name.as_str()),
        Sexp::List(items, _) => items.iter().any(|i| contains_path_constructors(i)),
    }
}

/// Check if a theory's category has PathType structure (HoTT-aware).
/// Returns the path constructor names if found.
pub fn category_has_path_type(cat: &crate::category::CategoryDef) -> bool {
    cat.has_path_type()
}

/// Validate that an SMT query is safe to send to Z3.
/// Returns Err with explanation if the query would cause Axiom K contagion.
pub fn validate_truncation_boundary(
    lhs: &Sexp,
    rhs: &Sexp,
    is_hott_theory: bool,
) -> std::result::Result<(), String> {
    if !is_hott_theory {
        return Ok(());
    }

    let lhs_has_paths = contains_path_constructors(lhs);
    let rhs_has_paths = contains_path_constructors(rhs);

    if lhs_has_paths || rhs_has_paths {
        Err(format!(
            "Axiom K contagion: cannot send proof-relevant path terms to Z3. \
             Z3 is proof-irrelevant and would collapse higher homotopies. \
             The offending term contains path constructors ({}). \
             Only 0-truncated (Set) or (-1)-truncated (Prop) types may use SMT oracle.",
            if lhs_has_paths { "LHS" } else { "RHS" }
        ))
    } else {
        Ok(())
    }
}

/// Check for universe lift cycles in rewrite rules.
/// Rules like `lift(A) ==> A` or `A ==> lift(A)` can create infinite
/// e-graph expansion: A = lift(A) = lift(lift(A)) = ...
/// Returns names of rules that form potential lift cycles.
pub fn detect_lift_cycles(rules: &[crate::session::VonNeumannRule]) -> Vec<String> {
    let lift_names: &[&str] = &["lift", "Lift", "cumul", "Cumul"];
    let mut cyclic = Vec::new();

    for rule in rules {
        let lhs_str = format!("{}", rule.lhs);
        let rhs_str = format!("{}", rule.rhs);

        // Pattern: [lift ?X] ==> ?X  or  ?X ==> [lift ?X]
        // These are individually fine, but BOTH directions create a cycle.
        // Also catch: [lift ?X] ==> [lift [lift ?X]] (expanding lift)
        for &lift in lift_names {
            let lhs_has_lift = lhs_str.contains(lift);
            let rhs_has_lift = rhs_str.contains(lift);

            // Expanding: LHS has fewer lifts than RHS (lift proliferation)
            if !lhs_has_lift && rhs_has_lift {
                // Rule introduces lift on RHS — potential infinite expansion
                cyclic.push(format!("{} (introduces {} on RHS)", rule.name, lift));
            }
            // Also catch nested lift expansion: [lift ?X] ==> [lift [lift ?X]]
            if lhs_has_lift && rhs_has_lift {
                let lhs_count = lhs_str.matches(lift).count();
                let rhs_count = rhs_str.matches(lift).count();
                if rhs_count > lhs_count {
                    cyclic.push(format!("{} (lift count grows: {} → {})", rule.name, lhs_count, rhs_count));
                }
            }
        }
    }

    cyclic
}

/// Collect free variable names (atoms starting with lowercase, not operators).
fn collect_free_vars(sexp: &Sexp, vars: &mut HashSet<String>) {
    match sexp {
        Sexp::Atom(name, _) => {
            // Skip metavars, operators (uppercase first letter), and known constants
            if !name.starts_with('?')
                && !name.chars().next().map(|c| c.is_uppercase()).unwrap_or(false)
                && name.chars().all(|c| c.is_alphanumeric() || c == '_')
            {
                // This is a potential free variable or constant — skip for now
                // SMT encoding treats all atoms as uninterpreted constants
            }
        }
        Sexp::List(items, _) => {
            // Skip the head (function name), collect from args
            for item in items.iter().skip(1) {
                collect_free_vars(item, vars);
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn atom(s: &str) -> Sexp {
        Sexp::Atom(s.to_string(), Span::default())
    }

    fn list(items: Vec<Sexp>) -> Sexp {
        Sexp::List(items, Span::default())
    }

    #[test]
    fn sexp_to_smtlib2_atom() {
        assert_eq!(sexp_to_smtlib2(&atom("hello")), "hello");
    }

    #[test]
    fn sexp_to_smtlib2_metavar() {
        assert_eq!(sexp_to_smtlib2(&atom("?X")), "X");
    }

    #[test]
    fn sexp_to_smtlib2_compound() {
        let term = list(vec![atom("plus"), atom("a"), atom("b")]);
        assert_eq!(sexp_to_smtlib2(&term), "(plus a b)");
    }

    #[test]
    fn sexp_to_smtlib2_nested() {
        let term = list(vec![
            atom("eq"),
            list(vec![atom("plus"), atom("x"), atom("zero")]),
            atom("x"),
        ]);
        assert_eq!(sexp_to_smtlib2(&term), "(eq (plus x zero) x)");
    }

    #[test]
    fn encode_smtlib2_basic() {
        let sorts = vec![SmtSort { name: "Nat".into() }];
        let funcs = vec![SmtFunc {
            name: "plus".into(),
            arg_sorts: vec!["Nat".into(), "Nat".into()],
            ret_sort: "Nat".into(),
        }];
        let encoded = encode_smtlib2(&sorts, &funcs, &[], true);
        assert!(encoded.contains("(declare-sort Nat 0)"));
        assert!(encoded.contains("(declare-fun plus (Nat Nat) Nat)"));
        assert!(encoded.contains("(check-sat)"));
    }

    #[test]
    fn encode_equality_check_basic() {
        let sorts = vec![SmtSort { name: "Nat".into() }];
        let funcs = vec![SmtFunc {
            name: "plus".into(),
            arg_sorts: vec!["Nat".into(), "Nat".into()],
            ret_sort: "Nat".into(),
        }];
        let lhs = list(vec![atom("plus"), atom("x"), atom("zero")]);
        let rhs = atom("x");
        let encoded = encode_equality_check(
            &sorts, &funcs, &lhs, &rhs,
            &[("x".into(), "Nat".into()), ("zero".into(), "Nat".into())],
        );
        assert!(encoded.contains("(assert (not (= (plus x zero) x)))"));
    }

    #[test]
    fn z3_available_or_skip() {
        // Test Z3 integration if available, skip gracefully if not
        let result = run_z3("(check-sat)\n");
        match result {
            SmtResult::Sat => {} // Z3 found: empty theory is sat
            SmtResult::Error(e) if e.contains("spawn") => {
                eprintln!("Z3 not available, skipping SMT tests: {}", e);
                return;
            }
            other => {
                // Any response means Z3 is working
                eprintln!("Z3 responded: {:?}", other);
            }
        }
    }

    #[test]
    fn z3_proves_trivial_equality() {
        // (not (= x x)) should be unsat
        let input = "(declare-const x Int)\n(assert (not (= x x)))\n(check-sat)\n";
        let result = run_z3(input);
        match result {
            SmtResult::Unsat => {} // correct
            SmtResult::Error(e) if e.contains("spawn") => {
                eprintln!("Z3 not available, skipping: {}", e);
                return;
            }
            other => panic!("Expected unsat, got: {:?}", other),
        }
    }

    // === TARTARUS: SMT Matching Loop Hang ===

    #[test]
    fn z3_timeout_on_quantifier_loop() {
        // This triggers a quantifier instantiation loop in Z3:
        // ∀x. f(x) = f(f(x)) with a query about a distant relation.
        // Without rlimit/timeout, Z3 spins forever.
        let input = "\
(set-logic UF)
(declare-sort S 0)
(declare-fun f (S) S)
(declare-fun g (S) S)
(declare-const a S)
(declare-const b S)
(assert (forall ((x S)) (= (f x) (f (f x)))))
(assert (forall ((x S)) (= (g (f x)) (f (g x)))))
(assert (not (= (g (g (g (g (g (f a)))))) (f (g (g (g (g (g a)))))))))
(check-sat)
";
        let result = run_z3(input);
        match result {
            SmtResult::Error(e) if e.contains("spawn") => {
                eprintln!("Z3 not available, skipping: {}", e);
                return;
            }
            SmtResult::Error(e) if e.contains("timeout") || e.contains("killed") => {
                // CORRECT: the IPC layer killed Z3 before it hung forever
            }
            SmtResult::Unknown => {
                // CORRECT: Z3 hit rlimit and returned unknown
            }
            SmtResult::Sat | SmtResult::Unsat => {
                // Z3 actually solved it — acceptable (solver got lucky)
            }
            SmtResult::Error(e) => {
                // Any other error is suspicious but not a hang
                eprintln!("Z3 returned error (not a hang): {}", e);
            }
        }
        // The key assertion: this test MUST complete in bounded time.
        // If run_z3 blocks forever, the test framework will kill us.
    }

    #[test]
    fn rlimit_injected_into_payload() {
        // Verify that encode_smtlib2 injects rlimit to prevent Z3 hangs
        let encoded = encode_smtlib2(&[], &[], &[], true);
        assert!(encoded.contains("rlimit") || encoded.contains("timeout"),
            "SMT-LIB2 payload must include resource limit to prevent Z3 hangs.\n\
             Got: {}", encoded);
    }

    // === GÖDEL TIER: Axiom K Contagion ===

    #[test]
    fn detects_path_constructors_in_terms() {
        // refl, concat, inv, ap are HoTT path constructors
        assert!(contains_path_constructors(&atom("refl")));
        assert!(contains_path_constructors(&atom("concat")));
        assert!(contains_path_constructors(&list(vec![atom("ap"), atom("f"), atom("p")])));
        // Regular terms should pass
        assert!(!contains_path_constructors(&atom("plus")));
        assert!(!contains_path_constructors(&list(vec![atom("add"), atom("x"), atom("y")])));
    }

    #[test]
    fn detects_nested_path_constructors() {
        // Path constructor buried inside a larger term
        let deep = list(vec![
            atom("eq"),
            list(vec![atom("concat"), atom("p"), atom("q")]),
            atom("r"),
        ]);
        assert!(contains_path_constructors(&deep));
    }

    #[test]
    fn truncation_boundary_rejects_path_terms() {
        let lhs = list(vec![atom("concat"), atom("p"), atom("q")]);
        let rhs = atom("r");
        let result = validate_truncation_boundary(&lhs, &rhs, true);
        assert!(result.is_err());
        assert!(result.unwrap_err().contains("Axiom K contagion"));
    }

    #[test]
    fn truncation_boundary_allows_ground_terms() {
        let lhs = list(vec![atom("plus"), atom("x"), atom("zero")]);
        let rhs = atom("x");
        // Even in HoTT theory, ground arithmetic is 0-truncated and safe
        assert!(validate_truncation_boundary(&lhs, &rhs, true).is_ok());
    }

    #[test]
    fn truncation_boundary_noop_for_non_hott() {
        let lhs = list(vec![atom("concat"), atom("p"), atom("q")]);
        let rhs = atom("r");
        // Non-HoTT theory: no restriction
        assert!(validate_truncation_boundary(&lhs, &rhs, false).is_ok());
    }

    // === GÖDEL TIER: Cumulativity Loophole ===

    #[test]
    fn detects_lift_cycle_rhs_expansion() {
        // Rule: ?X ==> [lift ?X] — introduces lift on RHS, infinite expansion
        let rules = vec![crate::session::VonNeumannRule {
            name: "bad-cumul".to_string(),
            lhs: atom("?X"),
            rhs: list(vec![atom("lift"), atom("?X")]),
        }];
        let cycles = detect_lift_cycles(&rules);
        assert!(!cycles.is_empty(), "Should detect lift expansion: {:?}", cycles);
        assert!(cycles[0].contains("bad-cumul"));
    }

    #[test]
    fn detects_nested_lift_growth() {
        // Rule: [lift ?X] ==> [lift [lift ?X]] — lift count grows
        let rules = vec![crate::session::VonNeumannRule {
            name: "nested-lift".to_string(),
            lhs: list(vec![atom("lift"), atom("?X")]),
            rhs: list(vec![atom("lift"), list(vec![atom("lift"), atom("?X")])]),
        }];
        let cycles = detect_lift_cycles(&rules);
        assert!(!cycles.is_empty(), "Should detect nested lift growth");
    }

    #[test]
    fn allows_safe_lift_elimination() {
        // Rule: [lift ?X] ==> ?X — eliminates lift, no cycle
        let rules = vec![crate::session::VonNeumannRule {
            name: "lift-elim".to_string(),
            lhs: list(vec![atom("lift"), atom("?X")]),
            rhs: atom("?X"),
        }];
        let cycles = detect_lift_cycles(&rules);
        assert!(cycles.is_empty(), "Lift elimination is safe: {:?}", cycles);
    }

    #[test]
    fn z3_refutes_false_equality() {
        // (not (= 0 1)) should be sat (the negation is satisfiable)
        let input = "(assert (not (= 0 1)))\n(check-sat)\n";
        let result = run_z3(input);
        match result {
            SmtResult::Sat => {} // correct: 0 ≠ 1
            SmtResult::Error(e) if e.contains("spawn") => {
                eprintln!("Z3 not available, skipping: {}", e);
                return;
            }
            other => panic!("Expected sat (inequality), got: {:?}", other),
        }
    }
}
