//! SMT bridge: encode Sexp terms to SMT-LIB2, communicate with Z3,
//! and inject results back into the proof system.
//!
//! Three modes:
//! - **SMTOracle**: terminal decision procedure. Serialize goal to SMT-LIB2,
//!   get sat/unsat back. No e-graph.
//! - **SMTAssisted**: cooperative mode. E-graph runs normally, calls Z3
//!   for decidable fragments, injects equalities back.
//! - **SMTEncoding**: the AST→SMT-LIB2 serializer (used by both modes).

use apeiron::parser::{Sexp, Span};
use std::collections::{HashMap, HashSet};
use std::io::Write;
use std::process::{Command, Stdio};

/// SMT-LIB2 sort declaration
#[derive(Debug, Clone)]
pub struct SmtSort {
    pub name: String,
}

/// SMT-LIB2 function declaration
#[derive(Debug, Clone)]
pub struct SmtFunc {
    pub name: String,
    pub arg_sorts: Vec<String>,
    pub ret_sort: String,
}

/// Result from an SMT query
#[derive(Debug, Clone, PartialEq)]
pub enum SmtResult {
    Sat,
    Unsat,
    Unknown,
    Error(String),
}

/// Encode a set of theory declarations and an assertion into SMT-LIB2.
pub fn encode_smtlib2(
    sorts: &[SmtSort],
    funcs: &[SmtFunc],
    assertions: &[String],
    check_sat: bool,
) -> String {
    let mut out = String::new();
    out.push_str("; Auto-generated by Hyperion SMT bridge\n");
    out.push_str("(set-logic ALL)\n");

    // Declare sorts
    for sort in sorts {
        out.push_str(&format!("(declare-sort {} 0)\n", sort.name));
    }

    // Declare functions
    for func in funcs {
        let args = if func.arg_sorts.is_empty() {
            "()".to_string()
        } else {
            format!("({})", func.arg_sorts.join(" "))
        };
        out.push_str(&format!(
            "(declare-fun {} {} {})\n",
            func.name, args, func.ret_sort
        ));
    }

    // Assertions
    for assertion in assertions {
        out.push_str(&format!("(assert {})\n", assertion));
    }

    if check_sat {
        out.push_str("(check-sat)\n");
    }

    out
}

/// Convert a Hyperion Sexp term to SMT-LIB2 s-expression string.
/// Hyperion uses `[f a b]` brackets; SMT-LIB2 uses `(f a b)` parens.
pub fn sexp_to_smtlib2(sexp: &Sexp) -> String {
    match sexp {
        Sexp::Atom(name, _) => {
            // SMT-LIB2 doesn't like `?` prefix for variables
            if name.starts_with('?') {
                name[1..].to_string()
            } else {
                name.clone()
            }
        }
        Sexp::List(items, _) => {
            if items.is_empty() {
                return "()".to_string();
            }
            let parts: Vec<String> = items.iter().map(|i| sexp_to_smtlib2(i)).collect();
            format!("({})", parts.join(" "))
        }
    }
}

/// Extract sorts and functions from a VonNeumann theory for SMT encoding.
pub fn theory_to_smt_decls(
    sorts: &[String],
    morphism_types: &HashMap<String, (Vec<String>, String)>,
) -> (Vec<SmtSort>, Vec<SmtFunc>) {
    let smt_sorts: Vec<SmtSort> = sorts
        .iter()
        .map(|s| SmtSort { name: s.clone() })
        .collect();

    let smt_funcs: Vec<SmtFunc> = morphism_types
        .iter()
        .map(|(name, (args, ret))| SmtFunc {
            name: name.clone(),
            arg_sorts: args.clone(),
            ret_sort: ret.clone(),
        })
        .collect();

    (smt_sorts, smt_funcs)
}

/// Encode an assert-eq as an SMT validity check.
/// To prove `lhs = rhs`, we assert `(not (= lhs rhs))` and check for unsat.
pub fn encode_equality_check(
    sorts: &[SmtSort],
    funcs: &[SmtFunc],
    lhs: &Sexp,
    rhs: &Sexp,
    free_vars: &[(String, String)], // (var_name, sort)
) -> String {
    let mut out = encode_smtlib2(sorts, funcs, &[], false);

    // Declare free variables
    for (var, sort) in free_vars {
        out.push_str(&format!("(declare-const {} {})\n", var, sort));
    }

    // Assert negation of equality (prove by refutation)
    let lhs_smt = sexp_to_smtlib2(lhs);
    let rhs_smt = sexp_to_smtlib2(rhs);
    out.push_str(&format!("(assert (not (= {} {})))\n", lhs_smt, rhs_smt));
    out.push_str("(check-sat)\n");

    out
}

/// Run Z3 on an SMT-LIB2 input string.
/// Returns the result (sat/unsat/unknown).
pub fn run_z3(input: &str) -> SmtResult {
    let result = Command::new("z3")
        .arg("-in")
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn();

    let mut child = match result {
        Ok(c) => c,
        Err(e) => return SmtResult::Error(format!("failed to spawn z3: {}", e)),
    };

    // Write input to stdin
    if let Some(mut stdin) = child.stdin.take() {
        if let Err(e) = stdin.write_all(input.as_bytes()) {
            return SmtResult::Error(format!("failed to write to z3 stdin: {}", e));
        }
    }

    // Read output
    let output = match child.wait_with_output() {
        Ok(o) => o,
        Err(e) => return SmtResult::Error(format!("z3 process error: {}", e)),
    };

    let stdout = String::from_utf8_lossy(&output.stdout);
    let first_line = stdout.lines().next().unwrap_or("").trim();

    match first_line {
        "sat" => SmtResult::Sat,
        "unsat" => SmtResult::Unsat,
        "unknown" => SmtResult::Unknown,
        _ => SmtResult::Error(format!("unexpected z3 output: {}", stdout)),
    }
}

/// Prove an equality using Z3 (SMT oracle mode).
/// Returns Ok(()) if proved, Err(detail) if disproved or unknown.
pub fn prove_equality_z3(
    sorts: &[SmtSort],
    funcs: &[SmtFunc],
    lhs: &Sexp,
    rhs: &Sexp,
) -> Result<(), String> {
    // Collect free variables from both sides
    let mut free_vars = HashSet::new();
    collect_free_vars(lhs, &mut free_vars);
    collect_free_vars(rhs, &mut free_vars);

    // For now, assign all free vars to the first sort (simplified)
    let default_sort = sorts.first().map(|s| s.name.clone()).unwrap_or("Int".to_string());
    let var_decls: Vec<(String, String)> = free_vars
        .into_iter()
        .map(|v| (v, default_sort.clone()))
        .collect();

    let smtlib = encode_equality_check(sorts, funcs, lhs, rhs, &var_decls);
    let result = run_z3(&smtlib);

    match result {
        SmtResult::Unsat => Ok(()), // negation is unsat → equality holds
        SmtResult::Sat => Err("Z3: equality is falsifiable (sat)".to_string()),
        SmtResult::Unknown => Err("Z3: unknown (solver timeout or undecidable)".to_string()),
        SmtResult::Error(e) => Err(format!("Z3 error: {}", e)),
    }
}

/// Collect free variable names (atoms starting with lowercase, not operators).
fn collect_free_vars(sexp: &Sexp, vars: &mut HashSet<String>) {
    match sexp {
        Sexp::Atom(name, _) => {
            // Skip metavars, operators (uppercase first letter), and known constants
            if !name.starts_with('?')
                && !name.chars().next().map(|c| c.is_uppercase()).unwrap_or(false)
                && name.chars().all(|c| c.is_alphanumeric() || c == '_')
            {
                // This is a potential free variable or constant — skip for now
                // SMT encoding treats all atoms as uninterpreted constants
            }
        }
        Sexp::List(items, _) => {
            // Skip the head (function name), collect from args
            for item in items.iter().skip(1) {
                collect_free_vars(item, vars);
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn atom(s: &str) -> Sexp {
        Sexp::Atom(s.to_string(), Span::default())
    }

    fn list(items: Vec<Sexp>) -> Sexp {
        Sexp::List(items, Span::default())
    }

    #[test]
    fn sexp_to_smtlib2_atom() {
        assert_eq!(sexp_to_smtlib2(&atom("hello")), "hello");
    }

    #[test]
    fn sexp_to_smtlib2_metavar() {
        assert_eq!(sexp_to_smtlib2(&atom("?X")), "X");
    }

    #[test]
    fn sexp_to_smtlib2_compound() {
        let term = list(vec![atom("plus"), atom("a"), atom("b")]);
        assert_eq!(sexp_to_smtlib2(&term), "(plus a b)");
    }

    #[test]
    fn sexp_to_smtlib2_nested() {
        let term = list(vec![
            atom("eq"),
            list(vec![atom("plus"), atom("x"), atom("zero")]),
            atom("x"),
        ]);
        assert_eq!(sexp_to_smtlib2(&term), "(eq (plus x zero) x)");
    }

    #[test]
    fn encode_smtlib2_basic() {
        let sorts = vec![SmtSort { name: "Nat".into() }];
        let funcs = vec![SmtFunc {
            name: "plus".into(),
            arg_sorts: vec!["Nat".into(), "Nat".into()],
            ret_sort: "Nat".into(),
        }];
        let encoded = encode_smtlib2(&sorts, &funcs, &[], true);
        assert!(encoded.contains("(declare-sort Nat 0)"));
        assert!(encoded.contains("(declare-fun plus (Nat Nat) Nat)"));
        assert!(encoded.contains("(check-sat)"));
    }

    #[test]
    fn encode_equality_check_basic() {
        let sorts = vec![SmtSort { name: "Nat".into() }];
        let funcs = vec![SmtFunc {
            name: "plus".into(),
            arg_sorts: vec!["Nat".into(), "Nat".into()],
            ret_sort: "Nat".into(),
        }];
        let lhs = list(vec![atom("plus"), atom("x"), atom("zero")]);
        let rhs = atom("x");
        let encoded = encode_equality_check(
            &sorts, &funcs, &lhs, &rhs,
            &[("x".into(), "Nat".into()), ("zero".into(), "Nat".into())],
        );
        assert!(encoded.contains("(assert (not (= (plus x zero) x)))"));
    }

    #[test]
    fn z3_available_or_skip() {
        // Test Z3 integration if available, skip gracefully if not
        let result = run_z3("(check-sat)\n");
        match result {
            SmtResult::Sat => {} // Z3 found: empty theory is sat
            SmtResult::Error(e) if e.contains("spawn") => {
                eprintln!("Z3 not available, skipping SMT tests: {}", e);
                return;
            }
            other => {
                // Any response means Z3 is working
                eprintln!("Z3 responded: {:?}", other);
            }
        }
    }

    #[test]
    fn z3_proves_trivial_equality() {
        // (not (= x x)) should be unsat
        let input = "(declare-const x Int)\n(assert (not (= x x)))\n(check-sat)\n";
        let result = run_z3(input);
        match result {
            SmtResult::Unsat => {} // correct
            SmtResult::Error(e) if e.contains("spawn") => {
                eprintln!("Z3 not available, skipping: {}", e);
                return;
            }
            other => panic!("Expected unsat, got: {:?}", other),
        }
    }

    #[test]
    fn z3_refutes_false_equality() {
        // (not (= 0 1)) should be sat (the negation is satisfiable)
        let input = "(assert (not (= 0 1)))\n(check-sat)\n";
        let result = run_z3(input);
        match result {
            SmtResult::Sat => {} // correct: 0 ≠ 1
            SmtResult::Error(e) if e.contains("spawn") => {
                eprintln!("Z3 not available, skipping: {}", e);
                return;
            }
            other => panic!("Expected sat (inequality), got: {:?}", other),
        }
    }
}
