// ── Generated by: omega kompile examples/calc.omega --theory Calc ──
// ── Do not edit. Regenerate from the verified Omega theory. ──

#![feature(box_patterns)]

pub mod omega_generated;
pub use omega_generated::*;
