// ── Generated by: omega kompile examples/calc.omega --theory Calc ──
// ── Do not edit. Regenerate from the verified Omega theory. ──

#[derive(Debug, Clone, PartialEq)]
pub enum Nat {
    Z,
    S(Box<Nat>),
}

#[derive(Debug, Clone, PartialEq)]
pub enum Bool {
    True,
    False,
}

#[derive(Debug, Clone, PartialEq)]
pub enum Expr {
    Lit(Nat),
    AddExpr(Box<Expr>, Box<Expr>),
    MulExpr(Box<Expr>, Box<Expr>),
    SubExpr(Box<Expr>, Box<Expr>),
    PowExpr(Box<Expr>, Box<Expr>),
    FactExpr(Box<Expr>),
    IfExpr(Box<Expr>, Box<Expr>, Box<Expr>),
    LtExpr(Box<Expr>, Box<Expr>),
    MinExpr(Box<Expr>, Box<Expr>),
    MaxExpr(Box<Expr>, Box<Expr>),
}

pub trait CalcEffects {
    fn eff_print(&mut self, nat: Nat);
}

pub fn add(nat: Nat, nat1: Nat) -> Nat {
    match (nat, nat1) {
        (Nat::Z, m) => m,
        (Nat::S(box n), m) => Nat::S(Box::new(add(n, m))),
        _ => unreachable!(),
    }
}

pub fn bool_to_nat(bool: Bool) -> Nat {
    match bool {
        Bool::True => Nat::S(Box::new(Nat::Z)),
        Bool::False => Nat::Z,
        _ => unreachable!(),
    }
}

pub fn eval(expr: Expr) -> Nat {
    match expr {
        Expr::Lit(n) => n,
        Expr::AddExpr(box a, box b) => add(eval(a), eval(b)),
        Expr::MulExpr(box a, box b) => mul(eval(a), eval(b)),
        Expr::SubExpr(box a, box b) => sub(eval(a), eval(b)),
        Expr::PowExpr(box a, box b) => pow(eval(a), eval(b)),
        Expr::FactExpr(box a) => fact(eval(a)),
        Expr::IfExpr(box c, box t, box f) => if_nat(is_zero(eval(c)), eval(f), eval(t)),
        Expr::LtExpr(box a, box b) => bool_to_nat(lt(eval(a), eval(b))),
        Expr::MinExpr(box a, box b) => min(eval(a), eval(b)),
        Expr::MaxExpr(box a, box b) => max(eval(a), eval(b)),
        _ => unreachable!(),
    }
}

pub fn fact(nat: Nat) -> Nat {
    match nat {
        Nat::Z => Nat::S(Box::new(Nat::Z)),
        Nat::S(box n) => mul(Nat::S(Box::new(n.clone())), fact(n)),
        _ => unreachable!(),
    }
}

pub fn if_nat(bool: Bool, nat: Nat, nat1: Nat) -> Nat {
    match (bool, nat, nat1) {
        (Bool::True, x, _) => x,
        (Bool::False, _, y) => y,
        _ => unreachable!(),
    }
}

pub fn is_zero(nat: Nat) -> Bool {
    match nat {
        Nat::Z => Bool::True,
        Nat::S(box _) => Bool::False,
        _ => unreachable!(),
    }
}

pub fn lt(nat: Nat, nat1: Nat) -> Bool {
    match (nat, nat1) {
        (Nat::Z, Nat::Z) => Bool::False,
        (Nat::Z, Nat::S(box _)) => Bool::True,
        (Nat::S(box _), Nat::Z) => Bool::False,
        (Nat::S(box n), Nat::S(box m)) => lt(n, m),
        _ => unreachable!(),
    }
}

pub fn max(nat: Nat, nat1: Nat) -> Nat {
    match (nat, nat1) {
        (a, b) => if_nat(lt(a.clone(), b.clone()), b, a),
        _ => unreachable!(),
    }
}

pub fn min(nat: Nat, nat1: Nat) -> Nat {
    match (nat, nat1) {
        (a, b) => if_nat(lt(a.clone(), b.clone()), a, b),
        _ => unreachable!(),
    }
}

pub fn mul(nat: Nat, nat1: Nat) -> Nat {
    match (nat, nat1) {
        (Nat::Z, _) => Nat::Z,
        (Nat::S(box n), m) => add(m.clone(), mul(n, m)),
        _ => unreachable!(),
    }
}

pub fn pow(nat: Nat, nat1: Nat) -> Nat {
    match (nat, nat1) {
        (_, Nat::Z) => Nat::S(Box::new(Nat::Z)),
        (n, Nat::S(box m)) => mul(n.clone(), pow(n, m)),
        _ => unreachable!(),
    }
}

pub fn run(effects: &mut impl CalcEffects, expr: Expr) {
    match expr {
        e => effects.eff_print(eval(e)),
        _ => unreachable!(),
    }
}

pub fn sub(nat: Nat, nat1: Nat) -> Nat {
    match (nat, nat1) {
        (Nat::Z, _) => Nat::Z,
        (n, Nat::Z) => n,
        (Nat::S(box n), Nat::S(box m)) => sub(n, m),
        _ => unreachable!(),
    }
}
