// ── Generated by: omega kompile examples/tcp-state.omega --theory TcpState ──
// ── Do not edit. Regenerate from the verified Omega theory. ──

#[derive(Debug, Clone, PartialEq)]
pub enum State {
    Closed,
    Listen,
    SynRecvd,
    Established,
    FinWait,
}

#[derive(Debug, Clone, PartialEq)]
pub enum Event {
    EvListen,
    EvSyn,
    EvAck,
    EvData,
    EvFin,
    EvRst,
    EvClose,
}

#[derive(Debug, Clone, PartialEq)]
pub enum Bool {
    True,
    False,
}

pub fn can_send(state: State) -> Bool {
    match state {
        State::Established => Bool::True,
        State::Closed => Bool::False,
        State::Listen => Bool::False,
        State::SynRecvd => Bool::False,
        State::FinWait => Bool::False,
        _ => unreachable!(),
    }
}

pub fn is_open(state: State) -> Bool {
    match state {
        State::Established => Bool::True,
        State::SynRecvd => Bool::True,
        State::Closed => Bool::False,
        State::Listen => Bool::False,
        State::FinWait => Bool::False,
        _ => unreachable!(),
    }
}

pub fn step(state: State, event: Event) -> State {
    match (state, event) {
        (State::Closed, Event::EvListen) => State::Listen,
        (State::Listen, Event::EvSyn) => State::SynRecvd,
        (State::SynRecvd, Event::EvAck) => State::Established,
        (State::Established, Event::EvData) => State::Established,
        (State::Established, Event::EvFin) => State::FinWait,
        (State::FinWait, Event::EvAck) => State::Closed,
        (State::Listen, Event::EvRst) => State::Closed,
        (State::SynRecvd, Event::EvRst) => State::Closed,
        (State::Established, Event::EvRst) => State::Closed,
        (State::FinWait, Event::EvRst) => State::Closed,
        _ => unreachable!(),
    }
}
